import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { randomUUID } from "crypto";
import { PermissionEnforcer } from "../core/permission-enforcer.js";
import { initializeSandbox } from "../core/sandbox-bootstrap.js";
import { ObserveRecorder } from "../core/observe-recorder.js";
import { synthesizeManifest } from "../core/manifest-synthesizer.js";
import { runHarness } from "../core/index.js";
import type { CheckRecord } from "../core/permission-enforcer.js";
import type { KaizenConfig } from "../types/plugin.js";
import type { PluginPermissions } from "../types/plugin.js";

export async function runPluginDevObserve(args: {
  pluginName: string;
  pluginDir: string;
  outDir: string;
  kaizenConfig: KaizenConfig;
}): Promise<number> {
  const sessionId = randomUUID();
  const enforcer = new PermissionEnforcer({ mode: "observe" });
  initializeSandbox(enforcer);
  const recorder = new ObserveRecorder(args.outDir, sessionId);
  const all: CheckRecord[] = [];
  enforcer.onCheck((r) => { all.push(r); recorder.record(r); });

  const outPath = join(args.pluginDir, ".kaizen", "proposed-permissions.ts");
  let finalized = false;
  const finalize = (): void => {
    if (finalized) return;
    finalized = true;
    recorder.flushSync();
    const proposed = synthesizeManifest(args.pluginName, all);
    writePluginPermissionsTs(outPath, args.pluginName, proposed);
    console.log(`kaizen plugin dev: proposed manifest written to ${outPath}`);
    console.log(`  records:    ${all.length}`);
    console.log(`  log file:   ${recorder.path_()}`);
  };

  const onSignal = (): void => { finalize(); process.exit(0); };
  process.on("SIGINT", onSignal);
  process.on("SIGTERM", onSignal);

  try {
    await runHarness({ kaizenConfig: args.kaizenConfig, enforcer });
  } finally {
    finalize();
    process.off("SIGINT", onSignal);
    process.off("SIGTERM", onSignal);
  }
  return 0;
}

function writePluginPermissionsTs(path: string, pluginName: string, manifest: PluginPermissions): void {
  mkdirSync(dirname(path), { recursive: true });
  const content = [
    `// Proposed permissions manifest for plugin '${pluginName}'.`,
    `// Generated by 'kaizen plugin dev --observe'. Review and paste into`,
    `// your plugin's default export under the \`permissions\` field.`,
    ``,
    `export const permissions = ${JSON.stringify(manifest, null, 2)} as const;`,
    ``,
  ].join("\n");
  writeFileSync(path, content);
}
